# Generated by Django 5.1.7 on 2025-03-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_collection_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='default-image.jpeg', upload_to='movies'),
        ),
    ]
