# Generated by Django 5.1.7 on 2025-03-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField(max_length=1500)),
                ('instructions', models.TextField(max_length=1500)),
                ('cooking_time', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipe/')),
            ],
        ),
    ]
